### ISSUE TITLE
Navigationsleiste ist unleserlich

### ISSUE THREAD

**Issue by kirel** [codeformuenster/codeformuenster.github.io_old#13]
Die Links in der Navigationsleiste haben zu wenig Kontrast. Da lassen sich die Farben optimieren. Dafür sollte vorher #14 erledigt werden.

**Comment by chk1** [comment]
Commit 3f19572cd21d02b1ddfe4b3805bd5b46b3502441 
Die Links sind jetzt besser zu lesen, der weiße Hintergrund ist weniger transparent und das Hintergrundbild insgesamt dunkler
