### ISSUE TITLE
Foto tauschen

### ISSUE THREAD

**Issue by milafrerichs** [codeformuenster/codeformuenster.github.io_old#4]

**Comment by ubergesundheit** [comment]
http://www.muenster.de/stadt/galerie/prinzipalmarkt_prinzipalmarkt15.html
und
http://www.muenster.de/stadt/galerie/prinzipalmarkt_prinzipalmarkt14.html

wären ähnlich zum aktuellen.. Ansonsten finde ich 
http://www.muenster.de/stadt/galerie/freizeit_aasee9.html
und
http://www.muenster.de/stadt/galerie/altstadt_turmlandschaft.html

ganz gut

**Comment by kirel** [comment]
http://www.muenster.de/stadt/galerie/prinzipalmarkt_prinzipalmarkt15.html hat super wiedererkennungswert und taugt glaube ich wegen der (geringen) Luminanz gut um Text drüber zu legen.
