### ISSUE TITLE
Links in der Beschreibung des nächsten Meetups

### ISSUE THREAD

**Issue by kirel** [codeformuenster/codeformuenster.github.io_old#8]
Links in der Beschreibung des nächsten Meetups sind nicht verlinkt. Vielleicht jagen wir die Beschreibung einfach durch Markdown? (z.B. via https://github.com/evilstreak/markdown-js)

**Comment by chk1** [comment]
Ist glaube ich nicht nötig, wenn #12 gelöst wurde. Wir velrinken ja in den Beschreibungen eh nicht so oft. 
Von Markdown in der Beschreibung würde ich auch absehen, da die Beschreibung in Emails usw. auch auftauchen, wo sie dann "kaputt" aussehen. Ebenfalls bei Suchmaschinen und Leuten ohne Javascript, wenn nachträglich über JS geparst wird.

**Comment by kirel** [comment]
+1
